name: scp files
on: 
    push:
        branches:
        - main
jobs:
  build_deploy:
     runs-on: ubuntu-latest

     steps:
      - name: "Build Da aplicação"
        uses: appleboy/ssh-action@v1
        with:
            host: "178.16.143.133"
            username: "root"
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
                cd ..
                cd /var/www/api-financial/api-financial-test
                git pull origin main
                npm install
                npm run migrations:run
                npm run build
                pm2 restart api-financial   