name: deployment apifinancial

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Instala Dependencias
        run: npm install

      - name: Run Migrations
        run: npm run migration:run
        
      - name: Build
        run: npm run build

      - name: pm2 restart
        run: pm2 restart apifinancial

  Deploy-Teste:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
      url: https://syslogicadev.com

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
         